//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.81.0.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IsNullable=false)]
public partial class Document {
    
    private CustomerPaymentStatusReportV03 cstmrPmtStsRptField;
    
    /// <comentarios/>
    public CustomerPaymentStatusReportV03 CstmrPmtStsRpt {
        get {
            return this.cstmrPmtStsRptField;
        }
        set {
            this.cstmrPmtStsRptField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CustomerPaymentStatusReportV03 {
    
    private GroupHeader36 grpHdrField;
    
    private OriginalGroupInformation20 orgnlGrpInfAndStsField;
    
    private OriginalPaymentInformation1[] orgnlPmtInfAndStsField;
    
    /// <comentarios/>
    public GroupHeader36 GrpHdr {
        get {
            return this.grpHdrField;
        }
        set {
            this.grpHdrField = value;
        }
    }
    
    /// <comentarios/>
    public OriginalGroupInformation20 OrgnlGrpInfAndSts {
        get {
            return this.orgnlGrpInfAndStsField;
        }
        set {
            this.orgnlGrpInfAndStsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("OrgnlPmtInfAndSts")]
    public OriginalPaymentInformation1[] OrgnlPmtInfAndSts {
        get {
            return this.orgnlPmtInfAndStsField;
        }
        set {
            this.orgnlPmtInfAndStsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class GroupHeader36 {
    
    private string msgIdField;
    
    private System.DateTime creDtTmField;
    
    private PartyIdentification32 initgPtyField;
    
    private BranchAndFinancialInstitutionIdentification4 fwdgAgtField;
    
    private BranchAndFinancialInstitutionIdentification4 dbtrAgtField;
    
    private BranchAndFinancialInstitutionIdentification4 cdtrAgtField;
    
    /// <comentarios/>
    public string MsgId {
        get {
            return this.msgIdField;
        }
        set {
            this.msgIdField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 FwdgAgt {
        get {
            return this.fwdgAgtField;
        }
        set {
            this.fwdgAgtField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 DbtrAgt {
        get {
            return this.dbtrAgtField;
        }
        set {
            this.dbtrAgtField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 CdtrAgt {
        get {
            return this.cdtrAgtField;
        }
        set {
            this.cdtrAgtField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PartyIdentification32 {
    
    private string nmField;
    
    private PostalAddress6 pstlAdrField;
    
    private Party6Choice idField;
    
    private string ctryOfResField;
    
    private ContactDetails2 ctctDtlsField;
    
    /// <comentarios/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <comentarios/>
    public PostalAddress6 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
    
    /// <comentarios/>
    public Party6Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public string CtryOfRes {
        get {
            return this.ctryOfResField;
        }
        set {
            this.ctryOfResField = value;
        }
    }
    
    /// <comentarios/>
    public ContactDetails2 CtctDtls {
        get {
            return this.ctctDtlsField;
        }
        set {
            this.ctctDtlsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PostalAddress6 {
    
    private AddressType2Code adrTpField;
    
    private bool adrTpFieldSpecified;
    
    private string deptField;
    
    private string subDeptField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    private string[] adrLineField;
    
    /// <comentarios/>
    public AddressType2Code AdrTp {
        get {
            return this.adrTpField;
        }
        set {
            this.adrTpField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdrTpSpecified {
        get {
            return this.adrTpFieldSpecified;
        }
        set {
            this.adrTpFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string Dept {
        get {
            return this.deptField;
        }
        set {
            this.deptField = value;
        }
    }
    
    /// <comentarios/>
    public string SubDept {
        get {
            return this.subDeptField;
        }
        set {
            this.subDeptField = value;
        }
    }
    
    /// <comentarios/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <comentarios/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <comentarios/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <comentarios/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <comentarios/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <comentarios/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum AddressType2Code {
    
    /// <comentarios/>
    ADDR,
    
    /// <comentarios/>
    PBOX,
    
    /// <comentarios/>
    HOME,
    
    /// <comentarios/>
    BIZZ,
    
    /// <comentarios/>
    MLTO,
    
    /// <comentarios/>
    DLVY,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CreditorReferenceType1Choice {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DocumentType3Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum DocumentType3Code {
    
    /// <comentarios/>
    RADM,
    
    /// <comentarios/>
    RPIN,
    
    /// <comentarios/>
    FXDR,
    
    /// <comentarios/>
    DISP,
    
    /// <comentarios/>
    PUOR,
    
    /// <comentarios/>
    SCOR,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CreditorReferenceType2 {
    
    private CreditorReferenceType1Choice cdOrPrtryField;
    
    private string issrField;
    
    /// <comentarios/>
    public CreditorReferenceType1Choice CdOrPrtry {
        get {
            return this.cdOrPrtryField;
        }
        set {
            this.cdOrPrtryField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CreditorReferenceInformation2 {
    
    private CreditorReferenceType2 tpField;
    
    private string refField;
    
    /// <comentarios/>
    public CreditorReferenceType2 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <comentarios/>
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class DocumentAdjustment1 {
    
    private ActiveOrHistoricCurrencyAndAmount amtField;
    
    private CreditDebitCode cdtDbtIndField;
    
    private bool cdtDbtIndFieldSpecified;
    
    private string rsnField;
    
    private string addtlInfField;
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <comentarios/>
    public CreditDebitCode CdtDbtInd {
        get {
            return this.cdtDbtIndField;
        }
        set {
            this.cdtDbtIndField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CdtDbtIndSpecified {
        get {
            return this.cdtDbtIndFieldSpecified;
        }
        set {
            this.cdtDbtIndFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
    
    /// <comentarios/>
    public string AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ActiveOrHistoricCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum CreditDebitCode {
    
    /// <comentarios/>
    CRDT,
    
    /// <comentarios/>
    DBIT,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class RemittanceAmount1 {
    
    private ActiveOrHistoricCurrencyAndAmount duePyblAmtField;
    
    private ActiveOrHistoricCurrencyAndAmount dscntApldAmtField;
    
    private ActiveOrHistoricCurrencyAndAmount cdtNoteAmtField;
    
    private ActiveOrHistoricCurrencyAndAmount taxAmtField;
    
    private DocumentAdjustment1[] adjstmntAmtAndRsnField;
    
    private ActiveOrHistoricCurrencyAndAmount rmtdAmtField;
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount DuePyblAmt {
        get {
            return this.duePyblAmtField;
        }
        set {
            this.duePyblAmtField = value;
        }
    }
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount DscntApldAmt {
        get {
            return this.dscntApldAmtField;
        }
        set {
            this.dscntApldAmtField = value;
        }
    }
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount CdtNoteAmt {
        get {
            return this.cdtNoteAmtField;
        }
        set {
            this.cdtNoteAmtField = value;
        }
    }
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount TaxAmt {
        get {
            return this.taxAmtField;
        }
        set {
            this.taxAmtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("AdjstmntAmtAndRsn")]
    public DocumentAdjustment1[] AdjstmntAmtAndRsn {
        get {
            return this.adjstmntAmtAndRsnField;
        }
        set {
            this.adjstmntAmtAndRsnField = value;
        }
    }
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount RmtdAmt {
        get {
            return this.rmtdAmtField;
        }
        set {
            this.rmtdAmtField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ReferredDocumentType1Choice {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DocumentType5Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum DocumentType5Code {
    
    /// <comentarios/>
    MSIN,
    
    /// <comentarios/>
    CNFA,
    
    /// <comentarios/>
    DNFA,
    
    /// <comentarios/>
    CINV,
    
    /// <comentarios/>
    CREN,
    
    /// <comentarios/>
    DEBN,
    
    /// <comentarios/>
    HIRI,
    
    /// <comentarios/>
    SBIN,
    
    /// <comentarios/>
    CMCN,
    
    /// <comentarios/>
    SOAC,
    
    /// <comentarios/>
    DISP,
    
    /// <comentarios/>
    BOLD,
    
    /// <comentarios/>
    VCHR,
    
    /// <comentarios/>
    AROI,
    
    /// <comentarios/>
    TSUT,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ReferredDocumentType2 {
    
    private ReferredDocumentType1Choice cdOrPrtryField;
    
    private string issrField;
    
    /// <comentarios/>
    public ReferredDocumentType1Choice CdOrPrtry {
        get {
            return this.cdOrPrtryField;
        }
        set {
            this.cdOrPrtryField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ReferredDocumentInformation3 {
    
    private ReferredDocumentType2 tpField;
    
    private string nbField;
    
    private System.DateTime rltdDtField;
    
    private bool rltdDtFieldSpecified;
    
    /// <comentarios/>
    public ReferredDocumentType2 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <comentarios/>
    public string Nb {
        get {
            return this.nbField;
        }
        set {
            this.nbField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime RltdDt {
        get {
            return this.rltdDtField;
        }
        set {
            this.rltdDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RltdDtSpecified {
        get {
            return this.rltdDtFieldSpecified;
        }
        set {
            this.rltdDtFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class StructuredRemittanceInformation7 {
    
    private ReferredDocumentInformation3[] rfrdDocInfField;
    
    private RemittanceAmount1 rfrdDocAmtField;
    
    private CreditorReferenceInformation2 cdtrRefInfField;
    
    private PartyIdentification32 invcrField;
    
    private PartyIdentification32 invceeField;
    
    private string[] addtlRmtInfField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("RfrdDocInf")]
    public ReferredDocumentInformation3[] RfrdDocInf {
        get {
            return this.rfrdDocInfField;
        }
        set {
            this.rfrdDocInfField = value;
        }
    }
    
    /// <comentarios/>
    public RemittanceAmount1 RfrdDocAmt {
        get {
            return this.rfrdDocAmtField;
        }
        set {
            this.rfrdDocAmtField = value;
        }
    }
    
    /// <comentarios/>
    public CreditorReferenceInformation2 CdtrRefInf {
        get {
            return this.cdtrRefInfField;
        }
        set {
            this.cdtrRefInfField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 Invcr {
        get {
            return this.invcrField;
        }
        set {
            this.invcrField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 Invcee {
        get {
            return this.invceeField;
        }
        set {
            this.invceeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlRmtInf")]
    public string[] AddtlRmtInf {
        get {
            return this.addtlRmtInfField;
        }
        set {
            this.addtlRmtInfField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class RemittanceInformation5 {
    
    private string[] ustrdField;
    
    private StructuredRemittanceInformation7[] strdField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Ustrd")]
    public string[] Ustrd {
        get {
            return this.ustrdField;
        }
        set {
            this.ustrdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Strd")]
    public StructuredRemittanceInformation7[] Strd {
        get {
            return this.strdField;
        }
        set {
            this.strdField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class AmendmentInformationDetails6 {
    
    private string orgnlMndtIdField;
    
    private PartyIdentification32 orgnlCdtrSchmeIdField;
    
    private BranchAndFinancialInstitutionIdentification4 orgnlCdtrAgtField;
    
    private CashAccount16 orgnlCdtrAgtAcctField;
    
    private PartyIdentification32 orgnlDbtrField;
    
    private CashAccount16 orgnlDbtrAcctField;
    
    private BranchAndFinancialInstitutionIdentification4 orgnlDbtrAgtField;
    
    private CashAccount16 orgnlDbtrAgtAcctField;
    
    private System.DateTime orgnlFnlColltnDtField;
    
    private bool orgnlFnlColltnDtFieldSpecified;
    
    private Frequency1Code orgnlFrqcyField;
    
    private bool orgnlFrqcyFieldSpecified;
    
    /// <comentarios/>
    public string OrgnlMndtId {
        get {
            return this.orgnlMndtIdField;
        }
        set {
            this.orgnlMndtIdField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 OrgnlCdtrSchmeId {
        get {
            return this.orgnlCdtrSchmeIdField;
        }
        set {
            this.orgnlCdtrSchmeIdField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 OrgnlCdtrAgt {
        get {
            return this.orgnlCdtrAgtField;
        }
        set {
            this.orgnlCdtrAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 OrgnlCdtrAgtAcct {
        get {
            return this.orgnlCdtrAgtAcctField;
        }
        set {
            this.orgnlCdtrAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 OrgnlDbtr {
        get {
            return this.orgnlDbtrField;
        }
        set {
            this.orgnlDbtrField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 OrgnlDbtrAcct {
        get {
            return this.orgnlDbtrAcctField;
        }
        set {
            this.orgnlDbtrAcctField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 OrgnlDbtrAgt {
        get {
            return this.orgnlDbtrAgtField;
        }
        set {
            this.orgnlDbtrAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 OrgnlDbtrAgtAcct {
        get {
            return this.orgnlDbtrAgtAcctField;
        }
        set {
            this.orgnlDbtrAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OrgnlFnlColltnDt {
        get {
            return this.orgnlFnlColltnDtField;
        }
        set {
            this.orgnlFnlColltnDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlFnlColltnDtSpecified {
        get {
            return this.orgnlFnlColltnDtFieldSpecified;
        }
        set {
            this.orgnlFnlColltnDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public Frequency1Code OrgnlFrqcy {
        get {
            return this.orgnlFrqcyField;
        }
        set {
            this.orgnlFrqcyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlFrqcySpecified {
        get {
            return this.orgnlFrqcyFieldSpecified;
        }
        set {
            this.orgnlFrqcyFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class BranchAndFinancialInstitutionIdentification4 {
    
    private FinancialInstitutionIdentification7 finInstnIdField;
    
    private BranchData2 brnchIdField;
    
    /// <comentarios/>
    public FinancialInstitutionIdentification7 FinInstnId {
        get {
            return this.finInstnIdField;
        }
        set {
            this.finInstnIdField = value;
        }
    }
    
    /// <comentarios/>
    public BranchData2 BrnchId {
        get {
            return this.brnchIdField;
        }
        set {
            this.brnchIdField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class FinancialInstitutionIdentification7 {
    
    private string bICField;
    
    private ClearingSystemMemberIdentification2 clrSysMmbIdField;
    
    private string nmField;
    
    private PostalAddress6 pstlAdrField;
    
    private GenericFinancialIdentification1 othrField;
    
    /// <comentarios/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
    
    /// <comentarios/>
    public ClearingSystemMemberIdentification2 ClrSysMmbId {
        get {
            return this.clrSysMmbIdField;
        }
        set {
            this.clrSysMmbIdField = value;
        }
    }
    
    /// <comentarios/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <comentarios/>
    public PostalAddress6 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
    
    /// <comentarios/>
    public GenericFinancialIdentification1 Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ClearingSystemMemberIdentification2 {
    
    private ClearingSystemIdentification2Choice clrSysIdField;
    
    private string mmbIdField;
    
    /// <comentarios/>
    public ClearingSystemIdentification2Choice ClrSysId {
        get {
            return this.clrSysIdField;
        }
        set {
            this.clrSysIdField = value;
        }
    }
    
    /// <comentarios/>
    public string MmbId {
        get {
            return this.mmbIdField;
        }
        set {
            this.mmbIdField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ClearingSystemIdentification2Choice {
    
    private string itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class GenericFinancialIdentification1 {
    
    private string idField;
    
    private FinancialIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <comentarios/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public FinancialIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class FinancialIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class BranchData2 {
    
    private string idField;
    
    private string nmField;
    
    private PostalAddress6 pstlAdrField;
    
    /// <comentarios/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <comentarios/>
    public PostalAddress6 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CashAccount16 {
    
    private AccountIdentification4Choice idField;
    
    private CashAccountType2 tpField;
    
    private string ccyField;
    
    private string nmField;
    
    /// <comentarios/>
    public AccountIdentification4Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccountType2 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <comentarios/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <comentarios/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class AccountIdentification4Choice {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class GenericAccountIdentification1 {
    
    private string idField;
    
    private AccountSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <comentarios/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public AccountSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class AccountSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType5 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType5 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType5 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CashAccountType2 {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CashAccountType4Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum CashAccountType4Code {
    
    /// <comentarios/>
    CASH,
    
    /// <comentarios/>
    CHAR,
    
    /// <comentarios/>
    COMM,
    
    /// <comentarios/>
    TAXE,
    
    /// <comentarios/>
    CISH,
    
    /// <comentarios/>
    TRAS,
    
    /// <comentarios/>
    SACC,
    
    /// <comentarios/>
    CACC,
    
    /// <comentarios/>
    SVGS,
    
    /// <comentarios/>
    ONDP,
    
    /// <comentarios/>
    MGLD,
    
    /// <comentarios/>
    NREX,
    
    /// <comentarios/>
    MOMA,
    
    /// <comentarios/>
    LOAN,
    
    /// <comentarios/>
    SLRY,
    
    /// <comentarios/>
    ODFT,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum Frequency1Code {
    
    /// <comentarios/>
    YEAR,
    
    /// <comentarios/>
    MNTH,
    
    /// <comentarios/>
    QURT,
    
    /// <comentarios/>
    MIAN,
    
    /// <comentarios/>
    WEEK,
    
    /// <comentarios/>
    DAIL,
    
    /// <comentarios/>
    ADHO,
    
    /// <comentarios/>
    INDA,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class MandateRelatedInformation6 {
    
    private string mndtIdField;
    
    private System.DateTime dtOfSgntrField;
    
    private bool dtOfSgntrFieldSpecified;
    
    private bool amdmntIndField;
    
    private bool amdmntIndFieldSpecified;
    
    private AmendmentInformationDetails6 amdmntInfDtlsField;
    
    private string elctrncSgntrField;
    
    private System.DateTime frstColltnDtField;
    
    private bool frstColltnDtFieldSpecified;
    
    private System.DateTime fnlColltnDtField;
    
    private bool fnlColltnDtFieldSpecified;
    
    private Frequency1Code frqcyField;
    
    private bool frqcyFieldSpecified;
    
    /// <comentarios/>
    public string MndtId {
        get {
            return this.mndtIdField;
        }
        set {
            this.mndtIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DtOfSgntr {
        get {
            return this.dtOfSgntrField;
        }
        set {
            this.dtOfSgntrField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtOfSgntrSpecified {
        get {
            return this.dtOfSgntrFieldSpecified;
        }
        set {
            this.dtOfSgntrFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public bool AmdmntInd {
        get {
            return this.amdmntIndField;
        }
        set {
            this.amdmntIndField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmdmntIndSpecified {
        get {
            return this.amdmntIndFieldSpecified;
        }
        set {
            this.amdmntIndFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public AmendmentInformationDetails6 AmdmntInfDtls {
        get {
            return this.amdmntInfDtlsField;
        }
        set {
            this.amdmntInfDtlsField = value;
        }
    }
    
    /// <comentarios/>
    public string ElctrncSgntr {
        get {
            return this.elctrncSgntrField;
        }
        set {
            this.elctrncSgntrField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FrstColltnDt {
        get {
            return this.frstColltnDtField;
        }
        set {
            this.frstColltnDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FrstColltnDtSpecified {
        get {
            return this.frstColltnDtFieldSpecified;
        }
        set {
            this.frstColltnDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FnlColltnDt {
        get {
            return this.fnlColltnDtField;
        }
        set {
            this.fnlColltnDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FnlColltnDtSpecified {
        get {
            return this.fnlColltnDtFieldSpecified;
        }
        set {
            this.fnlColltnDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public Frequency1Code Frqcy {
        get {
            return this.frqcyField;
        }
        set {
            this.frqcyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FrqcySpecified {
        get {
            return this.frqcyFieldSpecified;
        }
        set {
            this.frqcyFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class CategoryPurpose1Choice {
    
    private string itemField;
    
    private ItemChoiceType9 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType9 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType9 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class LocalInstrument2Choice {
    
    private string itemField;
    
    private ItemChoiceType8 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType8 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType8 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ServiceLevel8Choice {
    
    private string itemField;
    
    private ItemChoiceType7 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType7 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType7 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PaymentTypeInformation22 {
    
    private Priority2Code instrPrtyField;
    
    private bool instrPrtyFieldSpecified;
    
    private ClearingChannel2Code clrChanlField;
    
    private bool clrChanlFieldSpecified;
    
    private ServiceLevel8Choice svcLvlField;
    
    private LocalInstrument2Choice lclInstrmField;
    
    private SequenceType1Code seqTpField;
    
    private bool seqTpFieldSpecified;
    
    private CategoryPurpose1Choice ctgyPurpField;
    
    /// <comentarios/>
    public Priority2Code InstrPrty {
        get {
            return this.instrPrtyField;
        }
        set {
            this.instrPrtyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InstrPrtySpecified {
        get {
            return this.instrPrtyFieldSpecified;
        }
        set {
            this.instrPrtyFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public ClearingChannel2Code ClrChanl {
        get {
            return this.clrChanlField;
        }
        set {
            this.clrChanlField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClrChanlSpecified {
        get {
            return this.clrChanlFieldSpecified;
        }
        set {
            this.clrChanlFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public ServiceLevel8Choice SvcLvl {
        get {
            return this.svcLvlField;
        }
        set {
            this.svcLvlField = value;
        }
    }
    
    /// <comentarios/>
    public LocalInstrument2Choice LclInstrm {
        get {
            return this.lclInstrmField;
        }
        set {
            this.lclInstrmField = value;
        }
    }
    
    /// <comentarios/>
    public SequenceType1Code SeqTp {
        get {
            return this.seqTpField;
        }
        set {
            this.seqTpField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SeqTpSpecified {
        get {
            return this.seqTpFieldSpecified;
        }
        set {
            this.seqTpFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public CategoryPurpose1Choice CtgyPurp {
        get {
            return this.ctgyPurpField;
        }
        set {
            this.ctgyPurpField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum Priority2Code {
    
    /// <comentarios/>
    HIGH,
    
    /// <comentarios/>
    NORM,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum ClearingChannel2Code {
    
    /// <comentarios/>
    RTGS,
    
    /// <comentarios/>
    RTNS,
    
    /// <comentarios/>
    MPNS,
    
    /// <comentarios/>
    BOOK,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum SequenceType1Code {
    
    /// <comentarios/>
    FRST,
    
    /// <comentarios/>
    RCUR,
    
    /// <comentarios/>
    FNAL,
    
    /// <comentarios/>
    OOFF,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ClearingSystemIdentification3Choice {
    
    private string itemField;
    
    private ItemChoiceType6 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType6 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType6 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class SettlementInformation13 {
    
    private SettlementMethod1Code sttlmMtdField;
    
    private CashAccount16 sttlmAcctField;
    
    private ClearingSystemIdentification3Choice clrSysField;
    
    private BranchAndFinancialInstitutionIdentification4 instgRmbrsmntAgtField;
    
    private CashAccount16 instgRmbrsmntAgtAcctField;
    
    private BranchAndFinancialInstitutionIdentification4 instdRmbrsmntAgtField;
    
    private CashAccount16 instdRmbrsmntAgtAcctField;
    
    private BranchAndFinancialInstitutionIdentification4 thrdRmbrsmntAgtField;
    
    private CashAccount16 thrdRmbrsmntAgtAcctField;
    
    /// <comentarios/>
    public SettlementMethod1Code SttlmMtd {
        get {
            return this.sttlmMtdField;
        }
        set {
            this.sttlmMtdField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 SttlmAcct {
        get {
            return this.sttlmAcctField;
        }
        set {
            this.sttlmAcctField = value;
        }
    }
    
    /// <comentarios/>
    public ClearingSystemIdentification3Choice ClrSys {
        get {
            return this.clrSysField;
        }
        set {
            this.clrSysField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 InstgRmbrsmntAgt {
        get {
            return this.instgRmbrsmntAgtField;
        }
        set {
            this.instgRmbrsmntAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 InstgRmbrsmntAgtAcct {
        get {
            return this.instgRmbrsmntAgtAcctField;
        }
        set {
            this.instgRmbrsmntAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 InstdRmbrsmntAgt {
        get {
            return this.instdRmbrsmntAgtField;
        }
        set {
            this.instdRmbrsmntAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 InstdRmbrsmntAgtAcct {
        get {
            return this.instdRmbrsmntAgtAcctField;
        }
        set {
            this.instdRmbrsmntAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 ThrdRmbrsmntAgt {
        get {
            return this.thrdRmbrsmntAgtField;
        }
        set {
            this.thrdRmbrsmntAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 ThrdRmbrsmntAgtAcct {
        get {
            return this.thrdRmbrsmntAgtAcctField;
        }
        set {
            this.thrdRmbrsmntAgtAcctField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum SettlementMethod1Code {
    
    /// <comentarios/>
    INDA,
    
    /// <comentarios/>
    INGA,
    
    /// <comentarios/>
    COVE,
    
    /// <comentarios/>
    CLRG,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class EquivalentAmount2 {
    
    private ActiveOrHistoricCurrencyAndAmount amtField;
    
    private string ccyOfTrfField;
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <comentarios/>
    public string CcyOfTrf {
        get {
            return this.ccyOfTrfField;
        }
        set {
            this.ccyOfTrfField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class AmountType3Choice {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("EqvtAmt", typeof(EquivalentAmount2))]
    [System.Xml.Serialization.XmlElementAttribute("InstdAmt", typeof(ActiveOrHistoricCurrencyAndAmount))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class OriginalTransactionReference13 {
    
    private ActiveOrHistoricCurrencyAndAmount intrBkSttlmAmtField;
    
    private AmountType3Choice amtField;
    
    private System.DateTime intrBkSttlmDtField;
    
    private bool intrBkSttlmDtFieldSpecified;
    
    private System.DateTime reqdColltnDtField;
    
    private bool reqdColltnDtFieldSpecified;
    
    private System.DateTime reqdExctnDtField;
    
    private bool reqdExctnDtFieldSpecified;
    
    private PartyIdentification32 cdtrSchmeIdField;
    
    private SettlementInformation13 sttlmInfField;
    
    private PaymentTypeInformation22 pmtTpInfField;
    
    private PaymentMethod4Code pmtMtdField;
    
    private bool pmtMtdFieldSpecified;
    
    private MandateRelatedInformation6 mndtRltdInfField;
    
    private RemittanceInformation5 rmtInfField;
    
    private PartyIdentification32 ultmtDbtrField;
    
    private PartyIdentification32 dbtrField;
    
    private CashAccount16 dbtrAcctField;
    
    private BranchAndFinancialInstitutionIdentification4 dbtrAgtField;
    
    private CashAccount16 dbtrAgtAcctField;
    
    private BranchAndFinancialInstitutionIdentification4 cdtrAgtField;
    
    private CashAccount16 cdtrAgtAcctField;
    
    private PartyIdentification32 cdtrField;
    
    private CashAccount16 cdtrAcctField;
    
    private PartyIdentification32 ultmtCdtrField;
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount IntrBkSttlmAmt {
        get {
            return this.intrBkSttlmAmtField;
        }
        set {
            this.intrBkSttlmAmtField = value;
        }
    }
    
    /// <comentarios/>
    public AmountType3Choice Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime IntrBkSttlmDt {
        get {
            return this.intrBkSttlmDtField;
        }
        set {
            this.intrBkSttlmDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IntrBkSttlmDtSpecified {
        get {
            return this.intrBkSttlmDtFieldSpecified;
        }
        set {
            this.intrBkSttlmDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdColltnDt {
        get {
            return this.reqdColltnDtField;
        }
        set {
            this.reqdColltnDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqdColltnDtSpecified {
        get {
            return this.reqdColltnDtFieldSpecified;
        }
        set {
            this.reqdColltnDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdExctnDt {
        get {
            return this.reqdExctnDtField;
        }
        set {
            this.reqdExctnDtField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqdExctnDtSpecified {
        get {
            return this.reqdExctnDtFieldSpecified;
        }
        set {
            this.reqdExctnDtFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 CdtrSchmeId {
        get {
            return this.cdtrSchmeIdField;
        }
        set {
            this.cdtrSchmeIdField = value;
        }
    }
    
    /// <comentarios/>
    public SettlementInformation13 SttlmInf {
        get {
            return this.sttlmInfField;
        }
        set {
            this.sttlmInfField = value;
        }
    }
    
    /// <comentarios/>
    public PaymentTypeInformation22 PmtTpInf {
        get {
            return this.pmtTpInfField;
        }
        set {
            this.pmtTpInfField = value;
        }
    }
    
    /// <comentarios/>
    public PaymentMethod4Code PmtMtd {
        get {
            return this.pmtMtdField;
        }
        set {
            this.pmtMtdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PmtMtdSpecified {
        get {
            return this.pmtMtdFieldSpecified;
        }
        set {
            this.pmtMtdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public MandateRelatedInformation6 MndtRltdInf {
        get {
            return this.mndtRltdInfField;
        }
        set {
            this.mndtRltdInfField = value;
        }
    }
    
    /// <comentarios/>
    public RemittanceInformation5 RmtInf {
        get {
            return this.rmtInfField;
        }
        set {
            this.rmtInfField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 UltmtDbtr {
        get {
            return this.ultmtDbtrField;
        }
        set {
            this.ultmtDbtrField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 Dbtr {
        get {
            return this.dbtrField;
        }
        set {
            this.dbtrField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 DbtrAcct {
        get {
            return this.dbtrAcctField;
        }
        set {
            this.dbtrAcctField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 DbtrAgt {
        get {
            return this.dbtrAgtField;
        }
        set {
            this.dbtrAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 DbtrAgtAcct {
        get {
            return this.dbtrAgtAcctField;
        }
        set {
            this.dbtrAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 CdtrAgt {
        get {
            return this.cdtrAgtField;
        }
        set {
            this.cdtrAgtField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 CdtrAgtAcct {
        get {
            return this.cdtrAgtAcctField;
        }
        set {
            this.cdtrAgtAcctField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 Cdtr {
        get {
            return this.cdtrField;
        }
        set {
            this.cdtrField = value;
        }
    }
    
    /// <comentarios/>
    public CashAccount16 CdtrAcct {
        get {
            return this.cdtrAcctField;
        }
        set {
            this.cdtrAcctField = value;
        }
    }
    
    /// <comentarios/>
    public PartyIdentification32 UltmtCdtr {
        get {
            return this.ultmtCdtrField;
        }
        set {
            this.ultmtCdtrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum PaymentMethod4Code {
    
    /// <comentarios/>
    CHK,
    
    /// <comentarios/>
    TRF,
    
    /// <comentarios/>
    DD,
    
    /// <comentarios/>
    TRA,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ChargesInformation5 {
    
    private ActiveOrHistoricCurrencyAndAmount amtField;
    
    private BranchAndFinancialInstitutionIdentification4 ptyField;
    
    /// <comentarios/>
    public ActiveOrHistoricCurrencyAndAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <comentarios/>
    public BranchAndFinancialInstitutionIdentification4 Pty {
        get {
            return this.ptyField;
        }
        set {
            this.ptyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PaymentTransactionInformation25 {
    
    private string stsIdField;
    
    private string orgnlInstrIdField;
    
    private string orgnlEndToEndIdField;
    
    private TransactionIndividualStatus3Code txStsField;
    
    private bool txStsFieldSpecified;
    
    private StatusReasonInformation8[] stsRsnInfField;
    
    private ChargesInformation5[] chrgsInfField;
    
    private System.DateTime accptncDtTmField;
    
    private bool accptncDtTmFieldSpecified;
    
    private string acctSvcrRefField;
    
    private string clrSysRefField;
    
    private OriginalTransactionReference13 orgnlTxRefField;
    
    /// <comentarios/>
    public string StsId {
        get {
            return this.stsIdField;
        }
        set {
            this.stsIdField = value;
        }
    }
    
    /// <comentarios/>
    public string OrgnlInstrId {
        get {
            return this.orgnlInstrIdField;
        }
        set {
            this.orgnlInstrIdField = value;
        }
    }
    
    /// <comentarios/>
    public string OrgnlEndToEndId {
        get {
            return this.orgnlEndToEndIdField;
        }
        set {
            this.orgnlEndToEndIdField = value;
        }
    }
    
    /// <comentarios/>
    public TransactionIndividualStatus3Code TxSts {
        get {
            return this.txStsField;
        }
        set {
            this.txStsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TxStsSpecified {
        get {
            return this.txStsFieldSpecified;
        }
        set {
            this.txStsFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
    public StatusReasonInformation8[] StsRsnInf {
        get {
            return this.stsRsnInfField;
        }
        set {
            this.stsRsnInfField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("ChrgsInf")]
    public ChargesInformation5[] ChrgsInf {
        get {
            return this.chrgsInfField;
        }
        set {
            this.chrgsInfField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime AccptncDtTm {
        get {
            return this.accptncDtTmField;
        }
        set {
            this.accptncDtTmField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccptncDtTmSpecified {
        get {
            return this.accptncDtTmFieldSpecified;
        }
        set {
            this.accptncDtTmFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string AcctSvcrRef {
        get {
            return this.acctSvcrRefField;
        }
        set {
            this.acctSvcrRefField = value;
        }
    }
    
    /// <comentarios/>
    public string ClrSysRef {
        get {
            return this.clrSysRefField;
        }
        set {
            this.clrSysRefField = value;
        }
    }
    
    /// <comentarios/>
    public OriginalTransactionReference13 OrgnlTxRef {
        get {
            return this.orgnlTxRefField;
        }
        set {
            this.orgnlTxRefField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum TransactionIndividualStatus3Code {
    
    /// <comentarios/>
    ACTC,
    
    /// <comentarios/>
    RJCT,
    
    /// <comentarios/>
    PDNG,
    
    /// <comentarios/>
    ACCP,
    
    /// <comentarios/>
    ACSP,
    
    /// <comentarios/>
    ACSC,
    
    /// <comentarios/>
    ACWC,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class StatusReasonInformation8 {
    
    private PartyIdentification32 orgtrField;
    
    private StatusReason6Choice rsnField;
    
    private string[] addtlInfField;
    
    /// <comentarios/>
    public PartyIdentification32 Orgtr {
        get {
            return this.orgtrField;
        }
        set {
            this.orgtrField = value;
        }
    }
    
    /// <comentarios/>
    public StatusReason6Choice Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class StatusReason6Choice {
    
    private string itemField;
    
    private ItemChoiceType4 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType4 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class OriginalPaymentInformation1 {
    
    private string orgnlPmtInfIdField;
    
    private string orgnlNbOfTxsField;
    
    private decimal orgnlCtrlSumField;
    
    private bool orgnlCtrlSumFieldSpecified;
    
    private TransactionGroupStatus3Code pmtInfStsField;
    
    private bool pmtInfStsFieldSpecified;
    
    private StatusReasonInformation8[] stsRsnInfField;
    
    private NumberOfTransactionsPerStatus3[] nbOfTxsPerStsField;
    
    private PaymentTransactionInformation25[] txInfAndStsField;
    
    /// <comentarios/>
    public string OrgnlPmtInfId {
        get {
            return this.orgnlPmtInfIdField;
        }
        set {
            this.orgnlPmtInfIdField = value;
        }
    }
    
    /// <comentarios/>
    public string OrgnlNbOfTxs {
        get {
            return this.orgnlNbOfTxsField;
        }
        set {
            this.orgnlNbOfTxsField = value;
        }
    }
    
    /// <comentarios/>
    public decimal OrgnlCtrlSum {
        get {
            return this.orgnlCtrlSumField;
        }
        set {
            this.orgnlCtrlSumField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlCtrlSumSpecified {
        get {
            return this.orgnlCtrlSumFieldSpecified;
        }
        set {
            this.orgnlCtrlSumFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public TransactionGroupStatus3Code PmtInfSts {
        get {
            return this.pmtInfStsField;
        }
        set {
            this.pmtInfStsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PmtInfStsSpecified {
        get {
            return this.pmtInfStsFieldSpecified;
        }
        set {
            this.pmtInfStsFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
    public StatusReasonInformation8[] StsRsnInf {
        get {
            return this.stsRsnInfField;
        }
        set {
            this.stsRsnInfField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerSts")]
    public NumberOfTransactionsPerStatus3[] NbOfTxsPerSts {
        get {
            return this.nbOfTxsPerStsField;
        }
        set {
            this.nbOfTxsPerStsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("TxInfAndSts")]
    public PaymentTransactionInformation25[] TxInfAndSts {
        get {
            return this.txInfAndStsField;
        }
        set {
            this.txInfAndStsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum TransactionGroupStatus3Code {
    
    /// <comentarios/>
    ACTC,
    
    /// <comentarios/>
    RCVD,
    
    /// <comentarios/>
    PART,
    
    /// <comentarios/>
    RJCT,
    
    /// <comentarios/>
    PDNG,
    
    /// <comentarios/>
    ACCP,
    
    /// <comentarios/>
    ACSP,
    
    /// <comentarios/>
    ACSC,
    
    /// <comentarios/>
    ACWC,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class NumberOfTransactionsPerStatus3 {
    
    private string dtldNbOfTxsField;
    
    private TransactionIndividualStatus3Code dtldStsField;
    
    private decimal dtldCtrlSumField;
    
    private bool dtldCtrlSumFieldSpecified;
    
    /// <comentarios/>
    public string DtldNbOfTxs {
        get {
            return this.dtldNbOfTxsField;
        }
        set {
            this.dtldNbOfTxsField = value;
        }
    }
    
    /// <comentarios/>
    public TransactionIndividualStatus3Code DtldSts {
        get {
            return this.dtldStsField;
        }
        set {
            this.dtldStsField = value;
        }
    }
    
    /// <comentarios/>
    public decimal DtldCtrlSum {
        get {
            return this.dtldCtrlSumField;
        }
        set {
            this.dtldCtrlSumField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtldCtrlSumSpecified {
        get {
            return this.dtldCtrlSumFieldSpecified;
        }
        set {
            this.dtldCtrlSumFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class OriginalGroupInformation20 {
    
    private string orgnlMsgIdField;
    
    private string orgnlMsgNmIdField;
    
    private System.DateTime orgnlCreDtTmField;
    
    private bool orgnlCreDtTmFieldSpecified;
    
    private string orgnlNbOfTxsField;
    
    private decimal orgnlCtrlSumField;
    
    private bool orgnlCtrlSumFieldSpecified;
    
    private TransactionGroupStatus3Code grpStsField;
    
    private bool grpStsFieldSpecified;
    
    private StatusReasonInformation8[] stsRsnInfField;
    
    private NumberOfTransactionsPerStatus3[] nbOfTxsPerStsField;
    
    /// <comentarios/>
    public string OrgnlMsgId {
        get {
            return this.orgnlMsgIdField;
        }
        set {
            this.orgnlMsgIdField = value;
        }
    }
    
    /// <comentarios/>
    public string OrgnlMsgNmId {
        get {
            return this.orgnlMsgNmIdField;
        }
        set {
            this.orgnlMsgNmIdField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime OrgnlCreDtTm {
        get {
            return this.orgnlCreDtTmField;
        }
        set {
            this.orgnlCreDtTmField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlCreDtTmSpecified {
        get {
            return this.orgnlCreDtTmFieldSpecified;
        }
        set {
            this.orgnlCreDtTmFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string OrgnlNbOfTxs {
        get {
            return this.orgnlNbOfTxsField;
        }
        set {
            this.orgnlNbOfTxsField = value;
        }
    }
    
    /// <comentarios/>
    public decimal OrgnlCtrlSum {
        get {
            return this.orgnlCtrlSumField;
        }
        set {
            this.orgnlCtrlSumField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlCtrlSumSpecified {
        get {
            return this.orgnlCtrlSumFieldSpecified;
        }
        set {
            this.orgnlCtrlSumFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public TransactionGroupStatus3Code GrpSts {
        get {
            return this.grpStsField;
        }
        set {
            this.grpStsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GrpStsSpecified {
        get {
            return this.grpStsFieldSpecified;
        }
        set {
            this.grpStsFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
    public StatusReasonInformation8[] StsRsnInf {
        get {
            return this.stsRsnInfField;
        }
        set {
            this.stsRsnInfField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerSts")]
    public NumberOfTransactionsPerStatus3[] NbOfTxsPerSts {
        get {
            return this.nbOfTxsPerStsField;
        }
        set {
            this.nbOfTxsPerStsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class ContactDetails2 {
    
    private NamePrefix1Code nmPrfxField;
    
    private bool nmPrfxFieldSpecified;
    
    private string nmField;
    
    private string phneNbField;
    
    private string mobNbField;
    
    private string faxNbField;
    
    private string emailAdrField;
    
    private string othrField;
    
    /// <comentarios/>
    public NamePrefix1Code NmPrfx {
        get {
            return this.nmPrfxField;
        }
        set {
            this.nmPrfxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NmPrfxSpecified {
        get {
            return this.nmPrfxFieldSpecified;
        }
        set {
            this.nmPrfxFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <comentarios/>
    public string PhneNb {
        get {
            return this.phneNbField;
        }
        set {
            this.phneNbField = value;
        }
    }
    
    /// <comentarios/>
    public string MobNb {
        get {
            return this.mobNbField;
        }
        set {
            this.mobNbField = value;
        }
    }
    
    /// <comentarios/>
    public string FaxNb {
        get {
            return this.faxNbField;
        }
        set {
            this.faxNbField = value;
        }
    }
    
    /// <comentarios/>
    public string EmailAdr {
        get {
            return this.emailAdrField;
        }
        set {
            this.emailAdrField = value;
        }
    }
    
    /// <comentarios/>
    public string Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public enum NamePrefix1Code {
    
    /// <comentarios/>
    DOCT,
    
    /// <comentarios/>
    MIST,
    
    /// <comentarios/>
    MISS,
    
    /// <comentarios/>
    MADM,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PersonIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class GenericPersonIdentification1 {
    
    private string idField;
    
    private PersonIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <comentarios/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public PersonIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class DateAndPlaceOfBirth {
    
    private System.DateTime birthDtField;
    
    private string prvcOfBirthField;
    
    private string cityOfBirthField;
    
    private string ctryOfBirthField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDt {
        get {
            return this.birthDtField;
        }
        set {
            this.birthDtField = value;
        }
    }
    
    /// <comentarios/>
    public string PrvcOfBirth {
        get {
            return this.prvcOfBirthField;
        }
        set {
            this.prvcOfBirthField = value;
        }
    }
    
    /// <comentarios/>
    public string CityOfBirth {
        get {
            return this.cityOfBirthField;
        }
        set {
            this.cityOfBirthField = value;
        }
    }
    
    /// <comentarios/>
    public string CtryOfBirth {
        get {
            return this.ctryOfBirthField;
        }
        set {
            this.ctryOfBirthField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class PersonIdentification5 {
    
    private DateAndPlaceOfBirth dtAndPlcOfBirthField;
    
    private GenericPersonIdentification1[] othrField;
    
    /// <comentarios/>
    public DateAndPlaceOfBirth DtAndPlcOfBirth {
        get {
            return this.dtAndPlcOfBirthField;
        }
        set {
            this.dtAndPlcOfBirthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Othr")]
    public GenericPersonIdentification1[] Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class OrganisationIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <comentarios/>
    Cd,
    
    /// <comentarios/>
    Prtry,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class GenericOrganisationIdentification1 {
    
    private string idField;
    
    private OrganisationIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <comentarios/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public OrganisationIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <comentarios/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class OrganisationIdentification4 {
    
    private string bICOrBEIField;
    
    private GenericOrganisationIdentification1[] othrField;
    
    /// <comentarios/>
    public string BICOrBEI {
        get {
            return this.bICOrBEIField;
        }
        set {
            this.bICOrBEIField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Othr")]
    public GenericOrganisationIdentification1[] Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")]
public partial class Party6Choice {
    
    private object itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification4))]
    [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification5))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}
